// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Holiday[]>
) {
  const holidays: Holiday[] = generateHolidays();
  res.status(200).json(holidays);
}

function generateHolidays(): Holiday[] {
  return [
    {
      monthIndex: 0,
      day: 6,
      name: 'Duruthu - Poya Day',
      description: "Duruthu Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 0,
      day: 15,
      name: 'Tamil Thai Pongal Day',
      description: "Tamil Thai Pongal Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 0,
      day: 16,
      name: 'Special Bank Holiday',
      description: "Special Bank Holiday",
      isPublic: false,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 1,
      day: 4,
      name: 'National Day',
      description: "National Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 1,
      day: 5,
      name: 'Navam - Poya Day',
      description: "Navam Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 1,
      day: 18,
      name: "Maha Sivarathri Day",
      description: "Maha Sivarathri Day",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 2,
      day: 6,
      name: "Madin - Poya Day",
      description: "Madin Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 3,
      day: 5,
      name: "Bak - Poya Day",
      description: "Bak Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 3,
      day: 7,
      name: "Good Friday",
      description: "Good Friday",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 3,
      day: 13,
      name: "DP - Sinhala & Tamil New Year",
      description: "Day Prior to Sinhala and Tamil New Year",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 3,
      day: 14,
      name: "Sinhala & Tamil New Year",
      description: "Sinhala & Tamil New Year",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 3,
      day: 22,
      name: "Ramzan Festival Day",
      description: "Eid al-Fitr (Ramzan Festival)",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 4,
      day: 1,
      name: "May Day",
      description: "May Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 4,
      day: 5,
      name: "Vesak - Poya Day",
      description: "Vesak Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 4,
      day: 6,
      name: "DA - Vesak Poya Day",
      description: "Day after Vesak Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 5,
      day: 3,
      name: "Poson - Poya Day",
      description: "Poson Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 5,
      day: 29,
      name: "Hajj Festival Day",
      description: "Eid al-Adha (Hajj Festival Day)",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 6,
      day: 3,
      name: "Adhi Esala - Poya Day",
      description: "Adhi Esala Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 7,
      day: 1,
      name: "Esala - Poya Day",
      description: "Esala Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 7,
      day: 30,
      name: "Nikini - Poya Day",
      description: "Nikini Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 8,
      day: 28,
      name: "Holy Prophet's Birthday",
      description: "Milad-Un-Nabi (Holy Prophet's Birthday)",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 8,
      day: 29,
      name: "Binara - Poya Day",
      description: "Binara Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 9,
      day: 28,
      name: "Vap - Poya Day",
      description: "Vap Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 10,
      day: 12,
      name: "Deepavali Festival Day",
      description: "Deepavali Festival Day",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 10,
      day: 26,
      name: "Ill - Poya Day",
      description: "Ill Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 11,
      day: 25,
      name: "Christmas Day",
      description: "Christmas Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 11,
      day: 26,
      name: "Unduvap - Poya Day",
      description: "Unduvap Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
  ];
}
