// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Holiday[]>
) {
  const holidays: Holiday[] = generateHolidays();
  res.status(200).json(holidays);
}

function generateHolidays(): Holiday[] {
  return [
    {
      monthIndex: 0,
      day: 6,
      description: "Duruthu Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 0,
      day: 15,
      description: "Tamil Thai Pongal Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 0,
      day: 16,
      description: "Special Bank Holiday",
      isPublic: false,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 1,
      day: 4,
      description: "National Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 1,
      day: 5,
      description: "Navam Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 1,
      day: 18,
      description: "Maha Sivarathri Day",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 2,
      day: 6,
      description: "Madin Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 3,
      day: 5,
      description: "Bak Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 3,
      day: 7,
      description: "Good Friday",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 3,
      day: 13,
      description: "Day Prior to Sinhala & Tamil New Year",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 3,
      day: 14,
      description: "Sinhala & Tamil New Year",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 3,
      day: 22,
      description: "Eid al-Fitr (Ramzan Festival)",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 4,
      day: 1,
      description: "May Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 4,
      day: 5,
      description: "Vesak Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 4,
      day: 6,
      description: "Day after Vesak Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 5,
      day: 3,
      description: "Poson Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 5,
      day: 29,
      description: "Eid al-Adha (Hajj Festival Day)",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 6,
      day: 3,
      description: "Adhi Esala Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 7,
      day: 1,
      description: "Esala Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 7,
      day: 30,
      description: "Nikini Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 8,
      day: 28,
      description: "Milad-Un-Nabi (Holy Prophet's Birthday)",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 8,
      day: 29,
      description: "Binara Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 9,
      day: 28,
      description: "Vap Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 10,
      day: 12,
      description: "Deepavali Festival Day",
      isPublic: true,
      isBank: true,
      isMercantile: false,
    },
    {
      monthIndex: 10,
      day: 26,
      description: "Ill Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 11,
      day: 25,
      description: "Christmas Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
    {
      monthIndex: 11,
      day: 26,
      description: "Unduvap Full Moon Poya Day",
      isPublic: true,
      isBank: true,
      isMercantile: true,
    },
  ];
}
