import Head from "next/head";
import Month from "./components/Month";

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:3000/api/calendar2023`);
  const data = await res.json();

  return { props: { months: data } };
}

type Props = {
  months: Month[];
};

export default function Home({ months }: Props) {
  return (
    <>
      <Head>
        <title>Sri Lankan Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1 className="text-5xl font-bold text-center p-4">
          Sri Lankan Calendar - 2023
        </h1>
        {months?.length > 0 && <Month months={months} />}
      </main>
    </>
  );
}
